# Generated by Django 2.0.6 on 2019-03-03 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('decont', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='decont',
            options={'ordering': ['-perioada_start'], 'verbose_name': 'Decont', 'verbose_name_plural': 'Deconturi'},
        ),
        migrations.RenameField(
            model_name='decont',
            old_name='activitatea',
            new_name='activitate',
        ),
    ]
