# Generated by Django 2.0.6 on 2019-03-03 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decont', '0002_auto_20190303_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decont',
            name='data_decont',
            field=models.DateField(),
        ),
    ]
