# Generated by Django 2.0.6 on 2019-03-03 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decont', '0003_auto_20190303_1502'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='linieavans',
            options={'verbose_name': 'Sumă avansată', 'verbose_name_plural': 'Sume avansate'},
        ),
        migrations.AlterModelOptions(
            name='liniedecont',
            options={'verbose_name': 'Linie decont', 'verbose_name_plural': 'Linii decont'},
        ),
        migrations.AddField(
            model_name='linieavans',
            name='fisier',
            field=models.FileField(blank=True, null=True, upload_to='fisiere/'),
        ),
        migrations.AddField(
            model_name='liniedecont',
            name='fisier',
            field=models.FileField(blank=True, null=True, upload_to='fisiere/'),
        ),
    ]
